---
- name: Create a VM from a template
  hosts: localhost
  gather_facts: no
  tasks:
  - name: Clone the Template
    vmware_guest:
      hostname: "{{lookup('env', 'VMWARE_HOST')}}"
      username: "{{lookup('env', 'VMWARE_USER')}}"
      password: "{{lookup('env', 'VMWARE_PASSWORD')}}"
      datacenter: Datacenter-test01
      cluster: CL
      name: "{{vmname}}{{item}}"
      folder: /Datacenter-test01/vm
      template: "{{template}}"
      networks:
      - name: VM Network
        type: dhcp
      state: poweredon
      datastore: datastore1
      validate_certs: no
    with_sequence: count={{number|int - 1}}

  - name: Clone the Template with wait for customization
    vmware_guest:
      hostname: "{{lookup('env', 'VMWARE_HOST')}}"
      username: "{{lookup('env', 'VMWARE_USER')}}"
      password: "{{lookup('env', 'VMWARE_PASSWORD')}}"
      datacenter: Datacenter-test01
      cluster: CL
      name: "{{vmname}}{{number}}"
      folder: /Datacenter-test01/vm
      template: "{{template}}"
      networks:
      - name: VM Network
        type: dhcp
      state: poweredon
      datastore: datastore1
      validate_certs: no
      wait_for_ip_address: yes
#      wait_for_customization: yes
