---
- name: Tag Control for VM
  hosts: localhost
  gather_facts: no
  tasks:
    - name: Manage VM Tag
      vmware_tag_manager:
        hostname: "{{lookup('env', 'VMWARE_HOST')}}"
        username: "{{lookup('env', 'VMWARE_USER')}}"
        password: "{{lookup('env', 'VMWARE_PASSWORD')}}"
        validate_certs: False
        tag_names: New_VM
        object_name: " {{vmname}} "
        object_type: VirtualMachine
        state: "{{tag_state}}"
