---
- name: Tag Control for VM
  hosts: 192.168.10.9
  gather_facts: no
  tasks:
    - name: Info VM Tag
      vmware_tag_info:
        hostname: "{{lookup('env', 'VMWARE_HOST')}}"
        username: "{{lookup('env', 'VMWARE_USER')}}"
        password: "{{lookup('env', 'VMWARE_PASSWORD')}}"
        validate_certs: False
      delegate_to: 192.168.10.9
      register: vm_info
      
    - debug:
        var: vm_info
