---
- name: Tag Control for VM
  hosts: localhost 
  gather_facts: no
  tasks:
    - name: Info VM Tag
      vmware_guest_info:
        hostname: "{{lookup('env', 'VMWARE_HOST')}}"
        username: "{{lookup('env', 'VMWARE_USER')}}"
        password: "{{lookup('env', 'VMWARE_PASSWORD')}}"
        datacenter: "{{ datacenter_name }}"
        folder: "{{ foloder_name }}"
        name: "{{ vm_name }}"
        validate_certs: False
      delegate_to: localhost
      register: vm_info
      
    - debug:
        var: vm_info
