---
- name: Tag Control for VM
  gather_facts: no
  hosts: 192.168.10.10
  tasks:
    - name: Manage VM Tag test
      vmware_tag_manager:
        hostname: "{{lookup('env', 'VMWARE_HOST')}}"
        username: "{{lookup('env', 'VMWARE_USER')}}"
        password: "{{lookup('env', 'VMWARE_PASSWORD')}}"
        validate_certs: False
        tag_names: 
          - New_VM
        object_name: "{{ vmname }}"
        object_type: VirtualMachine
        state: "{{ tag_state }}"
      delegate_to: 192.168.10.10

      register: vm_info
      
    - debug:
        var: vm_info
